
## Numerical definitions for categories
category_types = {
    'dir':          0,
    'text':         1,
    'iso':          2,
    'archive':      3,
    'binary':       4,
    'code':         5,
    'picture':      6,
    'audio':        7,
    'video':        8,
    'checksum':     9,
    'playlist':     10,
    'executable':   11,
}

## Mimetype categories
mimes = {
    'text': [
        'application/msword',
        'application/pdf',
        'application/postscript',
        'application/vnd.oasis.opendocument.text',
        'application/x-info',
        'application/x-texinfo',
        'application/xml',
        'chemical/x-chemdraw'
    ],
    'archive': [
        'application/mac-binhex40',
        'application/rar',
        'application/x-7z-compressed',
        'application/x-apple-diskimage',
        'application/x-bittorrent',
        'application/x-stuffit',
        'application/x-tar',
        'application/x-wingz',
        'application/zip'
    ],
    'iso': ['application/x-iso9660-image'],
    'code': [
        'application/x-tex-pk',
        'application/x-troff',
        'application/x-wais-source',
        'chemical/x-molconn-Z',
        'chemical/x-vamas-iso14976',
        'text/css',
        'text/x-c++src',
        'text/x-chdr',
        'text/x-csrc',
        'text/x-diff',
        'text/x-dsrc',
        'text/x-pascal',
        'text/x-perl',
        'text/x-python',
        'text/x-sh'
    ],
    'binary': [
        'application/octet-stream',
        'application/x-font',
        'application/x-ns-proxy-autoconfig'
    ],
    'checksum': [
        'application/pgp-keys',
        'application/pgp-signature',
        'application/x-md5',
        'application/x-sha1'
    ],
    'playlist': ['application/x-mpegURL'],
    'executable': ['application/x-msdos-program']
}

## Extension categories
extensions = {
    'text': [
        '1st',
        '2nd',
        'AUX',
        'NFO',
        'README',
        'accurip',
        'aux',
        'changes',
        'cisco',
        'cnf',
        'compilation_problems',
        'conf',
        'contrib',
        'decw$book',
        'delivery',
        'diz',
        'dos',
        'examples',
        'guide',
        'help',
        'hlp',
        'inf',
        'ini',
        'int',
        'log',
        'message',
        'mms',
        'msg',
        'nfo',
        'nfo~',
        'package_name',
        'pc',
        'projects',
        'sub',
        'text',
        'title_page',
        'tpu',
        'tpu$section',
        'url',
        'vest_me',
        'xml_stuff'
    ],
    'binary': [
        'IMA',
        'XB',
        'XM',
        'card',
        'db',
        'e',
        'fdl',
        'idx',
        'ipf_obj',
        'mar',
        'mem',
        'olb',
        'smc'
    ],
    'iso': ['CUE', 'IMG', 'cue', 'mdf', 'mds'],
    'audio': ['ac3', 'ass', 'mp3-missing'],
    'video': ['BUP', 'IFO', 'M4V', 'VOB', 'f4v', 'img', 'mp7', 'ogm', 'vob'],
    'checksum': ['pem', 'sha256', 'sha512'],
    'executable': [
        'alpha_exe',
        'alpha_map',
        'alpha_obj',
        'alpha_olb',
        'axp_exe',
        'com_orig',
        'exe_alp_v72',
        'exe_alp_v721',
        'exe_alp_v732',
        'exe_alp_v82',
        'exe_alpha',
        'exe_axp',
        'exe_axp_v62',
        'exe_axp_v72',
        'exe_axp_v721',
        'exe_axp_v731',
        'exe_axp_v732',
        'exe_axp_v82',
        'exe_i64_v82',
        'exe_i64_v821',
        'exe_v62',
        'exe_v71',
        'exe_v72',
        'exe_v721',
        'exe_v73',
        'exe_v732',
        'exe_vax',
        'i64_exe',
        'ia64_exe',
        'ia64_obj',
        'int_img',
        'int_img_axp',
        'ipf_exe',
        'ipf_map',
        'ipf_olb',
        'itanium_exe',
        'itanium_obj',
        'obj_alpha',
        'obj_ia64',
        'obj_vax',
        'olb_alpha',
        'vax_exe',
        'vax_map',
        'vax_obj',
        'vax_olb',
        'vax_vaxc_exe'
    ],
    'code': [
        '1_preformatted',
        'ac',
        'ad',
        'adb',
        'ads',
        'am',
        'asm',
        'awk',
        'b32',
        'bas',
        'blc',
        'bor',
        'build',
        'c_orig',
        'cld',
        'clp',
        'cob',
        'com_source',
        'cpl',
        'dcl',
        'def',
        'dj2',
        'djg',
        'dsm',
        'dsp',
        'dsw',
        'emx',
        'filter',
        'for',
        'gcc',
        'gnm',
        'gpr',
        'guess',
        'h_example',
        'h_in',
        'h_orig',
        'h_txt',
        'h_vms',
        'hlb',
        'icc',
        'icc',
        'in',
        'in_h',
        'inc',
        'iss',
        'jnl',
        'l',
        'lis',
        'm4',
        'macro',
        'macros',
        'main',
        'mak',
        'mbu',
        'mcl',
        'miff',
        'mlb',
        'msc',
        'nsi',
        'nt',
        'odl',
        'oldstyle',
        'opt',
        'opts',
        'os2',
        'pam',
        'postinst',
        'pov',
        'prj',
        'pup',
        'tab',
        'tab_c',
        'tab_h',
        'tbl',
        'tc',
        'tlb',
        'vc',
        'version',
        'vms_bash',
        'wavelet',
        'wnt',
        'xs',
        'y',
        'yy_c',
        'yy_c2',
        'yy_cc'
    ],
    'archive': [
        '1_gz',
        'BCK',
        'ace',
        'bck',
        'bz2',
        'cckd',
        'depot',
        'gz',
        'lsm',
        'nzb',
        'par2',
        'pcsi',
        'pcsi$compressed',
        'qpg',
        'srr',
        'srs',
        'tar-bz2',
        'tar-gz',
        'tif-gz',
        'tif_gz'
    ],
}
